### ISSUE TITLE
make decision on staging environment: cloudflare or aws or something else?

### ISSUE THREAD

**Issue by gobengo** [ipfs-elastic-provider/metrics-collector#13]
## Context

We want to start having a deployment of metrics-collector so that [elastic ipfs can send delivered to a metrics-collector](https://github.com/ipfs-elastic-provider/metrics-collector/issues/14).

metrics-collector is a pretty portable set of node.js scripts. We can deploy it to cloudflare and/or aws and/or something else.

We need to decide where to deploy to first as an integration environment.

Barring other input, it may be slightly easiest to deploy to cloudflare workers, as the `IndexerMetricsCollector` class depends on a persistent storage api that has so far been tested using the implementation made by cloudflare (npm `@miniflare/durable-objects`). otoh, if we decide we want prod to be on aws, it may not be worth spending time on cloudflare deployment.

**Comment by gobengo** [comment]
cc @alanshaw @mikeal

**Comment by mikeal** [comment]
we’re gonna build a lot of notification services in CF so putting it there makes sense. we may also want an instance in AWS for locality but we can do that later.
